insert into ciudad (nombre_ciudad, id_pais) values ('Codajás', 72);
insert into ciudad (nombre_ciudad, id_pais) values ('Zhongying', 31);
insert into ciudad (nombre_ciudad, id_pais) values ('Pakis', 54);
insert into ciudad (nombre_ciudad, id_pais) values ('Tchoban Bey', 78);
insert into ciudad (nombre_ciudad, id_pais) values ('Tanda', 61);
insert into ciudad (nombre_ciudad, id_pais) values ('Jequitinhonha', 76);
insert into ciudad (nombre_ciudad, id_pais) values ('Nankang', 65);
insert into ciudad (nombre_ciudad, id_pais) values ('Manique', 16);
insert into ciudad (nombre_ciudad, id_pais) values ('Charleston', 53);
insert into ciudad (nombre_ciudad, id_pais) values ('Victoria', 41);
insert into ciudad (nombre_ciudad, id_pais) values ('Koran', 84);
insert into ciudad (nombre_ciudad, id_pais) values ('Armavir', 74);
insert into ciudad (nombre_ciudad, id_pais) values ('Victoriaville', 94);
insert into ciudad (nombre_ciudad, id_pais) values ('Velikooktyabr’skiy', 46);
insert into ciudad (nombre_ciudad, id_pais) values ('Sremska Mitrovica', 10);
insert into ciudad (nombre_ciudad, id_pais) values ('Az Zuwaytīnah', 86);
insert into ciudad (nombre_ciudad, id_pais) values ('Wugong', 6);
insert into ciudad (nombre_ciudad, id_pais) values ('Tindog', 10);
insert into ciudad (nombre_ciudad, id_pais) values ('Yangshuo', 10);
insert into ciudad (nombre_ciudad, id_pais) values ('Gutang', 41);
insert into ciudad (nombre_ciudad, id_pais) values ('Krajan Puru', 49);
insert into ciudad (nombre_ciudad, id_pais) values ('Nadezhda', 79);
insert into ciudad (nombre_ciudad, id_pais) values ('Pando', 46);
insert into ciudad (nombre_ciudad, id_pais) values ('Santo Domingo', 94);
insert into ciudad (nombre_ciudad, id_pais) values ('Białobrzegi', 92);
insert into ciudad (nombre_ciudad, id_pais) values ('Poste du Lac', 53);
insert into ciudad (nombre_ciudad, id_pais) values ('Araguari', 80);
insert into ciudad (nombre_ciudad, id_pais) values ('Talangbetutu', 54);
insert into ciudad (nombre_ciudad, id_pais) values ('Naqadeh', 30);
insert into ciudad (nombre_ciudad, id_pais) values ('Omu Aran', 19);
insert into ciudad (nombre_ciudad, id_pais) values ('Kpalimé', 36);
insert into ciudad (nombre_ciudad, id_pais) values ('Shazhenxi', 27);
insert into ciudad (nombre_ciudad, id_pais) values ('Changbai', 18);
insert into ciudad (nombre_ciudad, id_pais) values ('Los Santos', 13);
insert into ciudad (nombre_ciudad, id_pais) values ('Gramoteino', 83);
insert into ciudad (nombre_ciudad, id_pais) values ('Querecotillo', 71);
insert into ciudad (nombre_ciudad, id_pais) values ('Louka', 89);
insert into ciudad (nombre_ciudad, id_pais) values ('Gómez', 20);
insert into ciudad (nombre_ciudad, id_pais) values ('Aţ Ţafīlah', 74);
insert into ciudad (nombre_ciudad, id_pais) values ('Konstantynów Łódzki', 58);
insert into ciudad (nombre_ciudad, id_pais) values ('Shāhpur Chākar', 64);
insert into ciudad (nombre_ciudad, id_pais) values ('Charleroi', 73);
insert into ciudad (nombre_ciudad, id_pais) values ('Maglaj', 74);
insert into ciudad (nombre_ciudad, id_pais) values ('Mocun', 97);
insert into ciudad (nombre_ciudad, id_pais) values ('Moss', 46);
insert into ciudad (nombre_ciudad, id_pais) values ('Zaliztsi', 22);
insert into ciudad (nombre_ciudad, id_pais) values ('Akron', 13);
insert into ciudad (nombre_ciudad, id_pais) values ('Ḩawf', 43);
insert into ciudad (nombre_ciudad, id_pais) values ('Podgornoye', 43);
insert into ciudad (nombre_ciudad, id_pais) values ('Stanovoye', 55);
insert into ciudad (nombre_ciudad, id_pais) values ('La Virginia', 6);
insert into ciudad (nombre_ciudad, id_pais) values ('Przelewice', 38);
insert into ciudad (nombre_ciudad, id_pais) values ('Ozherel’ye', 82);
insert into ciudad (nombre_ciudad, id_pais) values ('Poretskoye', 61);
insert into ciudad (nombre_ciudad, id_pais) values ('Simunul', 45);
insert into ciudad (nombre_ciudad, id_pais) values ('Krajan Tekung', 16);
insert into ciudad (nombre_ciudad, id_pais) values ('Évlalo', 66);
insert into ciudad (nombre_ciudad, id_pais) values ('Goim', 81);
insert into ciudad (nombre_ciudad, id_pais) values ('Huata', 78);
insert into ciudad (nombre_ciudad, id_pais) values ('Brisbane', 51);
insert into ciudad (nombre_ciudad, id_pais) values ('Yukuriawat', 78);
insert into ciudad (nombre_ciudad, id_pais) values ('Chittagong', 97);
insert into ciudad (nombre_ciudad, id_pais) values ('Qinā', 54);
insert into ciudad (nombre_ciudad, id_pais) values ('Fuying', 88);
insert into ciudad (nombre_ciudad, id_pais) values ('Xinglin', 61);
insert into ciudad (nombre_ciudad, id_pais) values ('Jenang Selatan', 88);
insert into ciudad (nombre_ciudad, id_pais) values ('Nevesinje', 83);
insert into ciudad (nombre_ciudad, id_pais) values ('Saint-Jean-de-Védas', 98);
insert into ciudad (nombre_ciudad, id_pais) values ('Pánormos', 59);
insert into ciudad (nombre_ciudad, id_pais) values ('San José de Colinas', 99);
insert into ciudad (nombre_ciudad, id_pais) values ('Paris 01', 26);
insert into ciudad (nombre_ciudad, id_pais) values ('Anjepy', 34);
insert into ciudad (nombre_ciudad, id_pais) values ('Udon Thani', 74);
insert into ciudad (nombre_ciudad, id_pais) values ('Jiangpan', 95);
insert into ciudad (nombre_ciudad, id_pais) values ('Pau', 89);
insert into ciudad (nombre_ciudad, id_pais) values ('Guatire', 87);
insert into ciudad (nombre_ciudad, id_pais) values ('Lauro de Freitas', 20);
insert into ciudad (nombre_ciudad, id_pais) values ('Hässelby', 47);
insert into ciudad (nombre_ciudad, id_pais) values ('Mompós', 73);
insert into ciudad (nombre_ciudad, id_pais) values ('Thị Xã Lai Châu', 77);
insert into ciudad (nombre_ciudad, id_pais) values ('Thạnh Phú', 28);
insert into ciudad (nombre_ciudad, id_pais) values ('Tanakbeak Daye', 84);
insert into ciudad (nombre_ciudad, id_pais) values ('Kuala Terengganu', 96);
insert into ciudad (nombre_ciudad, id_pais) values ('São Mateus', 8);
insert into ciudad (nombre_ciudad, id_pais) values ('Milano', 97);
insert into ciudad (nombre_ciudad, id_pais) values ('Charneca', 10);
insert into ciudad (nombre_ciudad, id_pais) values ('Bondowoso', 3);
insert into ciudad (nombre_ciudad, id_pais) values ('Rinconada', 59);
insert into ciudad (nombre_ciudad, id_pais) values ('Urrô', 42);
insert into ciudad (nombre_ciudad, id_pais) values ('Migori', 43);
insert into ciudad (nombre_ciudad, id_pais) values ('Pangkalan', 67);
insert into ciudad (nombre_ciudad, id_pais) values ('Pasonobenu', 67);
insert into ciudad (nombre_ciudad, id_pais) values ('Abelheira', 35);
insert into ciudad (nombre_ciudad, id_pais) values ('Ballylinan', 78);
insert into ciudad (nombre_ciudad, id_pais) values ('Isniq', 18);
insert into ciudad (nombre_ciudad, id_pais) values ('Teknāf', 38);
insert into ciudad (nombre_ciudad, id_pais) values ('Candelária', 67);
insert into ciudad (nombre_ciudad, id_pais) values ('Karanganyar', 95);
insert into ciudad (nombre_ciudad, id_pais) values ('Cabeçudos', 56);
insert into ciudad (nombre_ciudad, id_pais) values ('San Javier', 80);
insert into ciudad (nombre_ciudad, id_pais) values ('Roma', 46);
insert into ciudad (nombre_ciudad, id_pais) values ('Balyaga', 16);
insert into ciudad (nombre_ciudad, id_pais) values ('Jatiprahu', 83);
insert into ciudad (nombre_ciudad, id_pais) values ('Yashio-shi', 84);
insert into ciudad (nombre_ciudad, id_pais) values ('Qiaodi', 52);
insert into ciudad (nombre_ciudad, id_pais) values ('Xiamao', 93);
insert into ciudad (nombre_ciudad, id_pais) values ('Shestakovo', 36);
insert into ciudad (nombre_ciudad, id_pais) values ('Dykan’ka', 90);
insert into ciudad (nombre_ciudad, id_pais) values ('Mompós', 27);
insert into ciudad (nombre_ciudad, id_pais) values ('Huangtan', 83);
insert into ciudad (nombre_ciudad, id_pais) values ('Xiaohe', 2);
insert into ciudad (nombre_ciudad, id_pais) values ('Trần Văn Thời', 1);
insert into ciudad (nombre_ciudad, id_pais) values ('Vilppula', 35);
insert into ciudad (nombre_ciudad, id_pais) values ('Jiangchang', 17);
insert into ciudad (nombre_ciudad, id_pais) values ('Carvalhal Redondo', 31);
insert into ciudad (nombre_ciudad, id_pais) values ('Banaba', 65);
insert into ciudad (nombre_ciudad, id_pais) values ('Guilherand-Granges', 12);
insert into ciudad (nombre_ciudad, id_pais) values ('Jinji', 89);
insert into ciudad (nombre_ciudad, id_pais) values ('Dolní Kounice', 44);
insert into ciudad (nombre_ciudad, id_pais) values ('Cincinnati', 90);
insert into ciudad (nombre_ciudad, id_pais) values ('Kalyny', 27);
insert into ciudad (nombre_ciudad, id_pais) values ('Sangmu', 60);
insert into ciudad (nombre_ciudad, id_pais) values ('Chengmagang', 58);
insert into ciudad (nombre_ciudad, id_pais) values ('Uchimaru', 41);
insert into ciudad (nombre_ciudad, id_pais) values ('Chortkiv', 64);
insert into ciudad (nombre_ciudad, id_pais) values ('Plandirejo', 98);
insert into ciudad (nombre_ciudad, id_pais) values ('Jasień', 59);
insert into ciudad (nombre_ciudad, id_pais) values ('Omīdcheh', 66);
insert into ciudad (nombre_ciudad, id_pais) values ('Selaawi', 70);
insert into ciudad (nombre_ciudad, id_pais) values ('Caleufú', 29);
insert into ciudad (nombre_ciudad, id_pais) values ('Rathdrum', 92);
insert into ciudad (nombre_ciudad, id_pais) values ('Agassiz', 18);
insert into ciudad (nombre_ciudad, id_pais) values ('Dobřív', 56);
insert into ciudad (nombre_ciudad, id_pais) values ('Shiye', 9);
insert into ciudad (nombre_ciudad, id_pais) values ('Kirkton', 73);
insert into ciudad (nombre_ciudad, id_pais) values ('Panyindangan', 17);
insert into ciudad (nombre_ciudad, id_pais) values ('Charlotte', 99);
insert into ciudad (nombre_ciudad, id_pais) values ('Solânea', 21);
insert into ciudad (nombre_ciudad, id_pais) values ('Rogongon', 30);
insert into ciudad (nombre_ciudad, id_pais) values ('Ryki', 14);
insert into ciudad (nombre_ciudad, id_pais) values ('Obong', 82);
insert into ciudad (nombre_ciudad, id_pais) values ('Bella Vista', 89);
insert into ciudad (nombre_ciudad, id_pais) values ('Fajsławice', 32);
insert into ciudad (nombre_ciudad, id_pais) values ('Albion', 73);
insert into ciudad (nombre_ciudad, id_pais) values ('Cochrane', 14);
insert into ciudad (nombre_ciudad, id_pais) values ('Phonphisai', 69);
insert into ciudad (nombre_ciudad, id_pais) values ('Baqiao', 53);
insert into ciudad (nombre_ciudad, id_pais) values ('Dem’yanovo', 81);
insert into ciudad (nombre_ciudad, id_pais) values ('Konstantinovo', 28);
insert into ciudad (nombre_ciudad, id_pais) values ('Sukorejo', 62);
insert into ciudad (nombre_ciudad, id_pais) values ('Bojano', 49);
insert into ciudad (nombre_ciudad, id_pais) values ('Guder', 44);
insert into ciudad (nombre_ciudad, id_pais) values ('Jaboatão', 79);
insert into ciudad (nombre_ciudad, id_pais) values ('Fengpo', 4);
insert into ciudad (nombre_ciudad, id_pais) values ('Wangjiang', 22);
insert into ciudad (nombre_ciudad, id_pais) values ('Tauranga', 77);
insert into ciudad (nombre_ciudad, id_pais) values ('Szolnok', 67);
insert into ciudad (nombre_ciudad, id_pais) values ('Araras', 45);
insert into ciudad (nombre_ciudad, id_pais) values ('Anningqu', 38);
insert into ciudad (nombre_ciudad, id_pais) values ('Astghadzor', 47);
insert into ciudad (nombre_ciudad, id_pais) values ('Columbus', 30);
insert into ciudad (nombre_ciudad, id_pais) values ('Pongkor', 58);
insert into ciudad (nombre_ciudad, id_pais) values ('Kawengan', 94);
insert into ciudad (nombre_ciudad, id_pais) values ('Janagdong', 3);
insert into ciudad (nombre_ciudad, id_pais) values ('Azara', 36);
insert into ciudad (nombre_ciudad, id_pais) values ('Paços', 33);
insert into ciudad (nombre_ciudad, id_pais) values ('Xiahong', 78);
insert into ciudad (nombre_ciudad, id_pais) values ('Inyati', 8);
insert into ciudad (nombre_ciudad, id_pais) values ('Cashel', 23);
insert into ciudad (nombre_ciudad, id_pais) values ('Rabaul', 7);
insert into ciudad (nombre_ciudad, id_pais) values ('Kondangrege', 99);
insert into ciudad (nombre_ciudad, id_pais) values ('Amolatar', 97);
insert into ciudad (nombre_ciudad, id_pais) values ('Novoukrainskiy', 84);
insert into ciudad (nombre_ciudad, id_pais) values ('Kuvshinovo', 58);
insert into ciudad (nombre_ciudad, id_pais) values ('Gongming', 47);
insert into ciudad (nombre_ciudad, id_pais) values ('Malunda', 61);
insert into ciudad (nombre_ciudad, id_pais) values ('Ndom', 95);
insert into ciudad (nombre_ciudad, id_pais) values ('Sogati', 62);
insert into ciudad (nombre_ciudad, id_pais) values ('Szprotawa', 40);
insert into ciudad (nombre_ciudad, id_pais) values ('Cikadongdong', 18);
insert into ciudad (nombre_ciudad, id_pais) values ('Lelystad', 59);
insert into ciudad (nombre_ciudad, id_pais) values ('Kose', 9);
insert into ciudad (nombre_ciudad, id_pais) values ('Karangmulyo', 38);
insert into ciudad (nombre_ciudad, id_pais) values ('Burträsk', 76);
insert into ciudad (nombre_ciudad, id_pais) values ('Ochobo', 24);
insert into ciudad (nombre_ciudad, id_pais) values ('Huangjing', 18);
insert into ciudad (nombre_ciudad, id_pais) values ('Pamungguan', 94);
insert into ciudad (nombre_ciudad, id_pais) values ('Naranjito', 34);
insert into ciudad (nombre_ciudad, id_pais) values ('Paojan', 29);
insert into ciudad (nombre_ciudad, id_pais) values ('Calabaca', 56);
insert into ciudad (nombre_ciudad, id_pais) values ('Buritama', 30);
insert into ciudad (nombre_ciudad, id_pais) values ('Ji’an', 37);
insert into ciudad (nombre_ciudad, id_pais) values ('Võhma', 91);
insert into ciudad (nombre_ciudad, id_pais) values ('Longxi', 98);
insert into ciudad (nombre_ciudad, id_pais) values ('Espargos', 2);
insert into ciudad (nombre_ciudad, id_pais) values ('Nacka', 74);
insert into ciudad (nombre_ciudad, id_pais) values ('Wrząsowice', 23);
insert into ciudad (nombre_ciudad, id_pais) values ('Shizi', 29);
insert into ciudad (nombre_ciudad, id_pais) values ('Rābigh', 31);
insert into ciudad (nombre_ciudad, id_pais) values ('Épernay', 34);
insert into ciudad (nombre_ciudad, id_pais) values ('Bahía Blanca', 81),('Ciudad de Buenos Aires', 81),('Ezeiza', 81),
('Junín', 81),('La Plata', 81),('Mar del Plata', 81),('Necochea', 81);
insert into ciudad (nombre_ciudad, id_pais) values ('Catamarca', 82),('Resistencia', 83),('Comodoro Rivadavia', 84),
('Esquel', 84),('Puerto Madryn', 84),('Córdoba', 85),('Corrientes', 86);